---
title: Public vs Private Graphs in R | Plotly
name: Public vs Private Graphs
permalink: r/privacy/
description: How to set the privacy settings of plotly graphs in R.
layout: base
thumbnail: thumbnail/privacy.jpg
language: r
page_type: example_index
has_thumbnail: false
display_as: file_settings
---

# Privacy Settings in R

Since Version 2.0 (November 15, 2015), Plotly for R renders entirely locally by default, but you can also publish these graphs to the web via the `plotly_POST()` function. By default, `plotly_POST()` creates public graphs (which are free to create), but with a [plotly subscription](https://plot.ly/products/cloud/) you can easily make them private via the `sharing` argument.


```{r, echo = FALSE}
knitr::opts_chunk$set(message = FALSE, results = 'hide')
Sys.setenv("plotly_username"="RPlotBot")
Sys.setenv("plotly_api_key"="q0lz6r5efr")
```

```{r}
library(plotly)
plot_ly(x = c(0, 2, 4), y = c(0, 4, 2))
```

```{r}
plotly_POST(filename = "r-docs/public-graph")
```

```{r, eval = FALSE}
# returns a "secret" url that points to your graph
plotly_POST(filename = "r-docs/private-graph", sharing = "secret")
# only those logged into your paying account can view result
plotly_POST(filename = "r-docs/private-graph", sharing = "private")
```
