---
title: Bubble Charts in R | Examples | Plotly
name: Bubble Charts
permalink: r/bubble-charts/
description: How to make a bubble chart in R. A bubble chart is a scatter plot whose markers have variable color and size.
layout: base
thumbnail: thumbnail/bubble.jpg
language: r
page_type: example_index
has_thumbnail: true
display_as: chart_type
order: 2
output:
  html_document:
    keep_md: true
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
Sys.setenv("plotly_username"="RPlotBot")
Sys.setenv("plotly_api_key"="q0lz6r5efr")
```

# Basic Bubble Chart

```{r, results = 'hide'}
library(plotly)
d <- diamonds[sample(nrow(diamonds), 1000), ]
# note how size is automatically scaled
plot_ly(d, x = ~carat, y = ~price, size = ~carat)
```

```{r, echo=FALSE}
plotly_POST(filename="bubble/1")
```

```{r, results = 'hide'}
plot_ly(d, x = ~carat, y = ~price, text = ~paste("Clarity: ", clarity),
        color = ~carat, size = ~carat)
```

```{r, echo=FALSE}
plotly_POST(filename="bubble/2")
```
