---
title: Modifying Axes in R | Examples | Plotly
name: Axes
permalink: r/axes/
description: How to adjust axes properties in R. Seven examples of linear and logarithmic axes, axes titles, and styling and coloring axes and grid lines.
layout: base
thumbnail: /images/axes.png
language: r
page_type: example_index
has_thumbnail: false
display_as: layout_opt
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE)
Sys.setenv("plotly_username"="RPlotBot")
Sys.setenv("plotly_api_key"="q0lz6r5efr")
```

# Modifying Axes Properties in R

### Style Axes Ticks and Placement
```{r, message=FALSE}
library(plotly)
a <- list(
  autotick = FALSE,
  ticks = "outside",
  tick0 = 0,
  dtick = 0.25,
  ticklen = 5,
  tickwidth = 2,
  tickcolor = toRGB("blue")
)
s <- seq(1, 4, by = 0.25)
plot_ly(x = s, y = s) %>%
  layout(xaxis = a, yaxis = a,
  filename="r-docs/style-properties")
```

### Style Axes Title and Ticks Labels
```{r, message=FALSE}
library(plotly)
f1 <- list(
  family = "Arial, sans-serif",
  size = 18,
  color = "lightgrey"
)
f2 <- list(
  family = "Old Standard TT, serif",
  size = 14,
  color = "black"
)
a <- list(
  title = "AXIS TITLE",
  titlefont = f1,
  showticklabels = TRUE,
  tickangle = 45,
  tickfont = f2,
  exponentformat = "e",
  showexponent = "All"
)

s <- seq(0, 8)
plot_ly(x = s, y = s) %>%
  add_trace(y = rev(s)) %>%
  layout(xaxis = a, yaxis = a, showlegend = FALSE,
  filename="r-docs/style-axes-title")
```

### Style Axes and the Zero-Line
```{r, message=FALSE}
library(plotly)
ax <- list(
  zeroline = TRUE,
  showline = TRUE,
  mirror = "ticks",
  gridcolor = toRGB("gray50"),
  gridwidth = 2,
  zerolinecolor = toRGB("red"),
  zerolinewidth = 4,
  linecolor = toRGB("black"),
  linewidth = 6
)
s <- seq(-1, 4)
plot_ly(x = s, y = s) %>%
  layout(xaxis = ax, yaxis = ax,
  filename="r-docs/style-zero-line")
```

### Hide Axes Title, Lines, Ticks, and Labels
```{r, message=FALSE}
library(plotly)
ax <- list(
  title = "",
  zeroline = FALSE,
  showline = FALSE,
  showticklabels = FALSE,
  showgrid = FALSE
)

plot_ly(x = c(1, 2), y = c(1, 2), filename="r-docs/hide-axes") %>%
  layout(xaxis = ax, yaxis = ax)
```

### Reversed Axes
```{r, message=FALSE}
library(plotly)
plot_ly(x = c(1, 2), y = c(1, 2), filename="r-docs/reversed-axes") %>%
  layout(xaxis = list(autorange = "reversed"))
```

### Logarithmic Axes
```{r, message=FALSE}
library(plotly)
s <- seq(1, 8)
plot_ly(x = s, y = exp(s), name = "exponential", filename="r-docs/log-axes") %>%
  add_trace(y =  s, name = "linear") %>%
  layout(yaxis = list(type = "log"))
```

### Rangemode
```{r, message=FALSE}
library(plotly)
plot_ly(x = seq(2, 6, by = 2), y = seq(-3, 3, by = 3), filename="r-docs/rangemode") %>%
  layout(
    xaxis = list(rangemode = "tozero"),
    yaxis = list(rangemode = "nonnegative"))
```

### Manual ranges
```{r, message=FALSE}
library(plotly)
s <- seq(1, 8)
plot_ly(x = s, y = s, filename="r-docs/manual-range") %>%
  add_trace(y = rev(s)) %>%
  layout(
    xaxis = list(range = c(2, 5)),
    yaxis = list(range = c(2, 5)))
```
