---
title: Text and Annotations in R | Examples | Plotly
name: Text and Annotations
permalink: r/text-and-annotations/
description: How to add text labels and annotations to plots in R.
layout: base
thumbnail: thumbnail/text-and-annotations.jpg
language: r
page_type: example_index
has_thumbnail: false
display_as: layout_opt
output:
  html_document:
    keep_md: true
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
Sys.setenv("plotly_username"="RPlotBot")
Sys.setenv("plotly_api_key"="q0lz6r5efr")
```

### Text Mode

```{r, results = 'hide'}
library(plotly)

p <- plot_ly(
  x = c("giraffes", "orangutans", "monkeys"),
  y = c(20, 14, 23),
  name = "SF Zoo",
  type = "bar"
)
p
```

```{r, echo=FALSE}
plotly_POST(p, filename="bar/1")
```

### Hover Text

```{r, results = 'hide'}
plot_ly(mtcars, x = ~wt, y = ~mpg, text = rownames(mtcars)) %>%
  add_markers()
```

```{r, echo=FALSE}
plotly_POST(filename="text/hover")
```

### Styling Text

```{r, results = 'hide'}
t <- list(
  family = "sans serif",
  size = 18,
  color = toRGB("grey50")
)
plot_ly(mtcars, x = ~wt, y = ~mpg, text = rownames(mtcars)) %>%
  add_markers() %>%
  add_text(textfont = t, textposition = "top middle")
```

```{r, echo=FALSE}
plotly_POST(filename="text/style")
```

### Single Annotation

```{r, results = 'hide'}
m <- mtcars[which.max(mtcars$mpg), ]

a <- list(
  x = m$wt,
  y = m$mpg,
  text = rownames(m),
  xref = "x",
  yref = "y",
  showarrow = TRUE,
  arrowhead = 7,
  ax = 20,
  ay = -40
)

plot_ly(mtcars, x = ~wt, y = ~mpg) %>%
  add_markers() %>%
  layout(annotations = a)
```

```{r, echo=FALSE}
plotly_POST(filename="annotation/single")
```

### Multiple Annotations

```{r, results = 'hide'}
plot_ly(mtcars, x = ~wt, y = ~mpg, marker=list(size=10)) %>%
  add_annotations(x = mtcars$wt,
                  y = mtcars$mpg,
                  text = rownames(mtcars),
                  xref = "x",
                  yref = "y",
                  showarrow = TRUE,
                  arrowhead = 4,
                  arrowsize = .5,
                  ax = 20,
                  ay = -40)
```

```{r, echo=FALSE}
plotly_POST(filename="annotation/multiple")
```

### Custom Hover Text

```{r, results = 'hide'}
mtcars %>%
  plot_ly(x = ~disp, y = ~mpg, color = ~factor(cyl), size = ~wt) %>%
  add_markers(
    hoverinfo = "text",
    text = ~paste("Displacement = ", disp, "Miles Per Gallon = ", mpg)
  ) %>%
  layout(title ="Custom Hover Text")
```

```{r, echo=FALSE}
plotly_POST(filename="text/custom")
```
