---
title: Map Subplots And Small Multiples
name: Map Subplots And Small Multiples
permalink: r/map-subplots-and-small-multiples/
description: How to create map subplots and small multiples in R.
layout: base
thumbnail: thumbnail/map-subplots.jpg
language: r
page_type: example_index
has_thumbnail: true
display_as: maps
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE)
Sys.setenv("plotly_username"="RPlotBot")
Sys.setenv("plotly_api_key"="q0lz6r5efr")
```
# Map Subplots and Small Multiples

```{r, message=FALSE, height=900}
# US map small multiples
library(plotly)
library(dplyr)
df <- read.csv('https://raw.githubusercontent.com/plotly/datasets/master/1962_2006_walmart_store_openings.csv')

# common map properties
g <- list(scope = 'usa', showland = T, landcolor = toRGB("gray90"), showcountries = F, subunitcolor = toRGB("white"))

# year text labels
yrs <- unique(df$YEAR)
id <- seq_along(yrs)

# id for anchoring traces on different plots
df$id <- as.integer(factor(df$YEAR))

p <- lapply(
  unique(df$YEAR),
  function(year){
    invisible(return(
      plot_ly(
        filter(df, YEAR==year), type = "scattergeo", geo = paste0("geo", id)
      ) %>%
        add_trace(
          lon = ~LON, lat = ~LAT, 
          showlegend = F, mode = "markers",
          marker = list(color = toRGB("blue"), opacity = 0.5)
        ) %>%
        add_trace(
          lon = -78, lat = 47, mode = 'text', text = year
        ) %>%
        layout(
          title = 'New Walmart Stores per year 1962-2006<br> Source: <a href="http://www.econ.umn.edu/~holmes/data/WalMart/index.html">University of Minnesota</a>',
           geo = g,
           autosize = F,
           width = 1000,
           height = 900,
           hovermode = F,
           showlegend = F
        )
    ))
  }
)

subplot(p, nrows = 9)
```
