---
title: Line and Scatter Plots in R | Examples | Plotly
name: Line and Scatter Plots
permalink: r/line-and-scatter/
description: How to create line and scatter plots in R. Seven examples of basic and advanced scatter plots, time series line plots, colored charts, and density plots.
layout: base
thumbnail: thumbnail/line-and-scatter.jpg
language: r
page_type: example_index
has_thumbnail: true
display_as: chart_type
order: 1
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE)
Sys.setenv("plotly_username"="RPlotBot")
Sys.setenv("plotly_api_key"="q0lz6r5efr")
```
# Line and Scatter Plots in R

```{r, message=FALSE}
# Simple scatterplot
library(plotly)
plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length) %>%
  add_markers()
```

### Scatter Plot with Qualitative Colorscale
```{r, message=FALSE}
plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length) %>%
  add_markers(color = ~Species)
```

### ColorBrewer Palette Names
```{r, message=FALSE}
# By default, colors will 'span the gamut'
# scales::show_col(RColorBrewer::brewer.pal("Set1"))
plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length) %>%
  add_markers(color = ~Species, colors = "Set1")
```

### Custom Color Scales
```{r, message=FALSE}
# pass RGB or hex color codes directly to colors for finer control
pal <- RColorBrewer::brewer.pal(nlevels(iris$Species), "Set1")
plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length) %>%
  add_markers(color = ~Species, colors = pal)
```

### Adding Color and Size Mapping
```{r, message=FALSE}
library(plotly)
d <- diamonds[sample(nrow(diamonds), 1000), ]
# note how size is automatically scaled and added as hover text
plot_ly(d, x = ~carat, y = ~price, size = ~carat) %>%
  add_markers()

plot_ly(
  d, x = ~carat, y = ~price,
  text = ~paste("Clarity: ", clarity),
  color = ~carat, size = ~carat, opacity = ~carat
) %>%
  add_markers()
```

### Basic Time Series Plot with Loess Smooth
```{r, message=FALSE}
p <- plot_ly(economics, x = ~date, y = ~uempmed) %>%
  add_lines(name = "unemployment")
p %>% 
  add_trace(y = ~fitted(loess(uempmed ~ as.numeric(date))), name = "loess")
```

### Density Plot
```{r, message=FALSE}
dens <- with(diamonds, tapply(price, INDEX = cut, density))
df <- data.frame(
  x = unlist(lapply(dens, "[[", "x")),
  y = unlist(lapply(dens, "[[", "y")),
  cut = rep(names(dens), each = length(dens[[1]]$x))
)
plot_ly(df, x = ~x, y = ~y, color = ~cut) %>%
  add_lines()
```

### Line Interpolation Options
```{r, message=FALSE}
x <- 1:5
y <- c(1, 3, 2, 3, 1)
plot_ly(x = ~x) %>%
  add_lines(y = ~y, name = "linear", line = list(shape = "linear")) %>%
  add_lines(y = y + 5, name = "spline", line = list(shape = "spline")) %>%
  add_lines(y = y + 10, name = "vhv", line = list(shape = "vhv")) %>%
  add_lines(y = y + 15, name = "hvh", line = list(shape = "hvh")) %>%
  add_lines(y = y + 20, name = "vh", line = list(shape = "vh")) %>%
  add_lines(y = y + 25, name = "hv", line = list(shape = "hv"))
```
