---
title: Heatmaps in R | Examples | Plotly
name: Heatmaps
permalink: r/heatmaps/
description: How to make a heatmap in R with a matrix. Seven examples of colored and labeled heatmaps with custom colorscales.
layout: base
thumbnail: thumbnail/heatmap.jpg
language: r
page_type: example_index
has_thumbnail: true
display_as: chart_type
order: 7
output: 
  html_document:
    keep_md: true
---

```{r, echo = FALSE}
knitr::opts_chunk$set(message = FALSE, results = 'hide')
Sys.setenv("plotly_username"="RPlotBot")
Sys.setenv("plotly_api_key"="q0lz6r5efr")
```

# Heatmaps in R

```{r}
library(plotly)
plot_ly(z = volcano, type = "heatmap")
```

```{r, echo=FALSE}
plotly_POST(filename="heatmap/simple")
```


### Categorical Axes

```{r}
m <- matrix(rnorm(9), nrow = 3, ncol = 3)
plot_ly(
	x = c("a", "b", "c"), y = c("d", "e", "f"),
	z = m, type = "heatmap"
)
```

```{r, echo=FALSE}
plotly_POST(filename="heatmap/cat")
```

### Sequential Colorscales: Greys

The `colors` argument understands color brewer palettes (see `RColorBrewer::brewer.pal.info` for valid names).

```{r}
plot_ly(z = volcano, colorscale = "Greys", type = "heatmap")
```

```{r, echo=FALSE}
plotly_POST(filename="heatmap/gray")
```

### Custom colorscales

The `colors` argument also accepts a color interpolation function like `colorRamp()`

```{r}
plot_ly(z = volcano, colors = colorRamp(c("red", "green")), type = "heatmap")
```

```{r, echo=FALSE}
plotly_POST(filename="heatmap/ramp")
```

Or, you can do the scaling yourself and use the colorscale attribute directly...

```{r}
vals <- unique(scales::rescale(c(volcano)))
o <- order(vals, decreasing = FALSE)
cols <- scales::col_numeric("Blues", domain = NULL)(vals)
colz <- setNames(data.frame(vals[o], cols[o]), NULL)
plot_ly(z = volcano, colorscale = colz, type = "heatmap")
```

```{r, echo=FALSE}
plotly_POST(filename="heatmap/custom")
```

