---
title: Bar Charts in R | Examples | Plotly
name: Bar Charts
permalink: r/bar-charts/
description: How to make a bar chart in R. Examples of grouped, stacked, overlaid, and colored bar charts.
layout: base
thumbnail: thumbnail/bar.jpg
language: r
page_type: example_index
has_thumbnail: true
display_as: chart_type
order: 2
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, results = 'hide')
Sys.setenv("plotly_username"="RPlotBot")
Sys.setenv("plotly_api_key"="q0lz6r5efr")
```

# Bar Charts in R

```{r}
library(plotly)
p <- plot_ly(
  x = c("giraffes", "orangutans", "monkeys"),
  y = c(20, 14, 23),
  name = "SF Zoo",
  type = "bar"
)
p
```

```{r, echo=FALSE}
plotly_POST(filename="bar/1")
```

```{r}
p2 <- add_trace(p, y = c(12, 18, 29), name = "LA Zoo")
p2
```

```{r, echo=FALSE}
plotly_POST(filename="bar/2")
```

```{r}
layout(p2, barmode = "stack")
```

```{r, echo=FALSE}
plotly_POST(filename="bar/3")
```

## customizing colors

```{r}
library(dplyr)
ggplot2::diamonds %>% count(cut) %>%
  plot_ly(x = ~cut, y = ~n, color = I("black"))
```

```{r, echo=FALSE}
plotly_POST(filename="bar/4")
```

# mapping a color variable

```{r}
ggplot2::diamonds %>% count(cut, clarity) %>%
  plot_ly(x = ~cut, y = ~n, color = ~clarity)
```

```{r, echo=FALSE}
plotly_POST(filename="bar/5")
```

