---
title: Error Bars in R | Examples | Plotly
name: Error Bars
permalink: r/error-bars/
description: How to add error bars to scatter plots in R.
layout: base
thumbnail: /images/error-bar.png
language: r
page_type: example_index
has_thumbnail: true
display_as: chart_type
order: 11
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE)
Sys.setenv("plotly_username"="RPlotBot")
Sys.setenv("plotly_api_key"="q0lz6r5efr")
```
# Error Bars

```{r, message=FALSE}


library(dplyr)
library(plotly)

p <- ggplot2::mpg %>% group_by(class) %>%
  summarise(mn = mean(hwy), sd = 1.96 * sd(hwy)) %>%
  arrange(desc(mn)) %>%
  plot_ly(x = class, y = mn, error_y = list(value = sd),
          mode = "markers", name = "Highway",
          filename="r-docs/basic-error-bars") %>%
  layout(yaxis = list(title = "Miles Per Gallon"))
p

df2 <- mpg %>% group_by(class) %>%
  summarise(mn = mean(cty), sd = 1.96 * sd(cty))

p2 <- add_trace(p, y = mn, error_y = list(value = sd),
          name = "City", data = df2,
          filename = "r-docs/basic-error-bars-2")
p2
```
