---
title: Legends in R | Examples | Plotly
name: Legends
permalink: r/legend/
description: How to modify the legend in R graphs. Seven examples of how to move, color, and hide the legend.
layout: base
thumbnail: thumbnail/legends.jpg
language: r
page_type: example_index
has_thumbnail: false
display_as: layout_opt
output: 
  html_document:
    keep_md: true
---

```{r, echo = FALSE}
knitr::opts_chunk$set(message = FALSE, results = 'hide')
Sys.setenv("plotly_username"="RPlotBot")
Sys.setenv("plotly_api_key"="q0lz6r5efr")
```

# Legend Properties in R

### Legend Names
```{r}
library(plotly)
p <- plot_ly(x = ~seq(1, 8)) %>%
  add_lines(y = ~rnorm(8), name = "Blue Trace") %>%
  add_lines(y = ~rnorm(8), name = "Orange Trace")
p
```

```{r, echo=FALSE}
plotly_POST(filename="legend/names")
```

### Hiding the Legend

```{r}
p %>% layout(showlegend = FALSE)
```

```{r, echo=FALSE}
plotly_POST(filename="legend/hiding")
```

### Positioning the Legend

```{r}
p %>% layout(legend = list(x = 0.5, y = 0))
```

```{r, echo=FALSE}
plotly_POST(filename="legend/position")
```

### Styling the Legend

```{r}
f <- list(
  family = "sans-serif",
  size = 12,
  color = "#000"
)
l <- list(
  font = f,
  bgcolor = "#E2E2E2",
  bordercolor = "#FFFFFF",
  borderwidth = 2
)
p %>% layout(legend = l)
```

```{r, echo=FALSE}
plotly_POST(filename="legend/style")
```

### Hiding Legend Entries

```{r}
plot_ly(x = ~seq(1, 8)) %>%
  add_trace(y = ~rnorm(8), showlegend = FALSE) %>%
  add_trace(y = ~rnorm(8), name = "Orange Trace")
```

```{r, echo=FALSE}
plotly_POST(filename="legend/entry")
```
