---
title: Box Plots in R | Examples | Plotly
name: Box Plots
permalink: r/box-plots/
description: How to make an interactive box plot in R. Examples of box plots in R that are grouped, colored, and display the underlying data distribution.
layout: base
thumbnail: thumbnail/box.jpg
language: r
page_type: example_index
has_thumbnail: true
display_as: chart_type
order: 1
---

```{r, echo = FALSE}
knitr::opts_chunk$set(message = FALSE, results = 'hide')
Sys.setenv("plotly_username"="RPlotBot")
Sys.setenv("plotly_api_key"="q0lz6r5efr")
```

# Box Plots

### basic boxplot

```{r}
library(plotly)
plot_ly(y = ~rnorm(50), type = "box") %>%
  add_trace(y = ~rnorm(50, 1))
```

```{r, echo=FALSE}
plotly_POST(filename="box/1")
```

### adding jittered points

```{r}
plot_ly(y = ~rnorm(50), type = "box", boxpoints = "all", jitter = 0.3,
        pointpos = -1.8)
```

```{r, echo=FALSE}
plotly_POST(filename="box/2")
```


### several box plots

```{r}
plot_ly(ggplot2::diamonds, y = ~price, color = ~cut, type = "box")
```

```{r, echo=FALSE}
plotly_POST(filename="box/3")
```

### grouped box plots

```{r}
plot_ly(ggplot2::diamonds, x = ~cut, y = ~price, color = ~clarity, type = "box") %>%
  layout(boxmode = "group")
```

```{r, echo=FALSE}
plotly_POST(filename="box/4")
```
