---
title: 3D Tri-Surf Plots in R | Examples | Plotly
name: 3D Tri-Surf Plots
permalink: r/trisurf/
description: How to make interactive 3D mesh plots in R.
layout: base
thumbnail: thumbnail/trisurf.jpg
language: r
page_type: example_index
has_thumbnail: true
display_as: 3d_charts
order: 17
output: 
  html_document:
    keep_md: true
---

```{r, echo = FALSE}
knitr::opts_chunk$set(message = FALSE, results = 'hide')
Sys.setenv("plotly_username"="RPlotBot")
Sys.setenv("plotly_api_key"="q0lz6r5efr")
```

# Basic Tri-Surf Plot

```{r}
library(plotly)

plot_ly(
  x = c(0, 1, 2, 0),
  y = c(0, 0, 1, 2),
  z = c(0, 2, 0, 1),
  i = c(0, 0, 0, 1),
  j = c(1, 2, 3, 2),
  k = c(2, 3, 1, 3),
  facecolor = toRGB(viridisLite::viridis(4))
)
```

```{r, echo=FALSE}
plotly_POST(filename="trisurf/1")
```


# Cube with Different Face Colors

```{r}
library(plotly)

plot_ly(
  x = c(0, 0, 1, 1, 0, 0, 1, 1),
  y = c(0, 1, 1, 0, 0, 1, 1, 0),
  z = c(0, 0, 0, 0, 1, 1, 1, 1),
  i = c(7, 0, 0, 0, 4, 4, 2, 6, 4, 0, 3, 7),
  j = c(3, 4, 1, 2, 5, 6, 5, 5, 0, 1, 2, 2),
  k = c(0, 7, 2, 3, 6, 7, 1, 2, 5, 5, 7, 6),
  facecolor = rep(toRGB(viridisLite::inferno(6)), each = 2)
)
```


```{r, echo=FALSE}
plotly_POST(filename="trisurf/2")
```

