---
title: Error Bars in R | Examples | Plotly
name: Error Bars
permalink: r/error-bars/
description: How to add error bars to scatter plots in R.
layout: base
thumbnail: thumbnail/error-bar.jpg
language: r
page_type: example_index
has_thumbnail: true
display_as: chart_type
order: 11
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE)
Sys.setenv("plotly_username"="RPlotBot")
Sys.setenv("plotly_api_key"="q0lz6r5efr")
```
# Error Bars

```{r, message=FALSE}

library(dplyr)
library(plotly)

data <- ggplot2::mpg %>% group_by(class) %>%
  summarise(mn = mean(hwy), sd = 1.96 * sd(hwy), mn_c = mean(cty)) %>%
  arrange(desc(mn))

p <- data %>%
  plot_ly(x = ~class, y = ~mn ) %>%
  add_trace(error_y = list(value=10), type = "bar", name = "Highway") %>%
  layout(yaxis = list(title = "Miles Per Gallon"))

p2 <- add_trace(p, y = ~mn_c, error_y = list(value=10),
                name = "City", type = "bar")
#by default the `type` for error is `percent`, which takes
#a percentage of the y value as the error bar.
p2
```
