signin('theengineear', 'o9zlr0hy6z')

trace1 = struct(...
  'x', { {'giraffes', 'orangutans', 'monkeys'} }, ...
  'y', [20, 14, 23], ...
  'name', 'SF Zoo', ...
  'marker', struct(...
    'line', struct('color', 'grey'), ...
    'color', 'orange'), ...
  'type', 'bar');
trace2 = struct(...
  'x', { {'giraffes', 'orangutans', 'monkeys'} }, ...
  'y', [12, 18, 29], ...
  'name', 'LA Zoo', ...
  'marker', struct(...
    'line', struct(...
      'color', 'grey', ...
      'width', 3), ...
    'color', 'blue'), ...
  'type', 'bar');
data = {trace1, trace2};
layout = struct(...
    'title', 'Animal Population', ...
    'xaxis', struct('type', 'category'), ...
    'yaxis', struct('title', '# of animals (thousands)'), ...
    'categories', { {'giraffes', 'orangutans', 'monkeys'} }, ...
    'barmode', 'group', ...
    'bargap', 0.25, ...
    'bargroupgap', 0.3, ...
    'orientation', 'v');

response = plotly(data, struct('layout', layout, 'filename', 'style-bar', 'fileopt', 'overwrite', 'auto_open', 'false'));
plot_url = response.url