signin('test-runner', '9h29fe3l0x')

x = randn(500,1);
y = randn(500,1)+1;

data = {...
  struct(...
    'x', x, ...
    'y', y, ...
    'type', 'histogram2d')...
};

response = plotly(data, struct('filename', '2d-histogram', 'fileopt', 'overwrite'));
plot_url = response.url