signin('test-runner', '9h29fe3l0x')

data = {...
  struct(...
    'x', { {'giraffes', 'orangutans', 'monkeys'} }, ...
    'y', [20, 14, 23], ...
    'type', 'bar')...
};

response = plotly(data, struct('filename', 'basic-bar', 'fileopt', 'overwrite'));
plot_url = response.url