signin('test-runner', '9h29fe3l0x')

x = randn(500,1);

data = {...
  struct(...
    'x', x, ...
    'type', 'histogram')...
};

response = plotly(data, struct('filename', 'basic-histogram', 'fileopt', 'overwrite'));
plot_url = response.url