signin('test-runner', '9h29fe3l0x')

trace1 = struct(...
  'x', [0, 1, 2, 3], ...
  'y', [0, 2, 4, 6], ...
  'visible', true);
trace2 = struct(...
  'x', [0, 1, 2, 3], ...
  'y', [8, 4, 2, 0], ...
  'visible', false);
data = {trace0, trace1};

response = plotly(data, struct('filename', 'data-visible', 'fileopt', 'overwrite'));
plot_url = response.url