signin('test-runner', '9h29fe3l0x')

data = {...
  struct(...
    'x', [1, 2, 3, 4], ...
    'y', [2, 1, 3, 4], ...
    'error_y', struct(...
      'value', 15, ...
      'type', 'percent', ...
      'symmetric', false, ...
      'valueminus', 25), ...
    'type', 'scatter')...
};

response = plotly(data, struct('filename', 'error-bar-asymmetric-constant', 'fileopt', 'overwrite'));
plot_url = response.url