signin('test-runner', '9h29fe3l0x')

data = {...
  struct(...
    'x', [1, 2, 3, 4], ...
    'y', [2, 1, 3, 4], ...
    'error_x', struct(...
      'value', 10, ...
      'type', 'percent'))...
};

response = plotly(data, struct('filename', 'error-bar-horizontal', 'fileopt', 'overwrite'));
plot_url = response.url