signin('test-runner', '9h29fe3l0x')

trace1 = struct(...
  'name', 'SF Zoo', ...
  'x', { {'giraffes', 'orangutans', 'monkeys'} }, ...
  'y', [20, 14, 23], ...
  'type', 'bar');
trace2 = struct(...
  'name', 'LA Zoo', ...
  'x', { {'giraffes', 'orangutans', 'monkeys'} }, ...
  'y', [12, 18, 29], ...
  'type', 'bar');
data = {trace0, trace1};

layout = struct(...
    'barmode', 'group', ...
    'xaxis', struct('type', 'category'), ...
    'categories', { {'giraffes', 'orangutans', 'monkeys'} });

response = plotly(data, struct('layout', layout, 'filename', 'grouped-bar', 'fileopt', 'overwrite'));
plot_url = response.url