signin('test-runner', '9h29fe3l0x')

trace1 = struct(...
  'x', [1, 2, 3], ...
  'y', [4, 5, 6], ...
  'type', 'scatter', ...
  'name', 'Experiment', ...
  'line', struct(...
    'color', 'rgb(3,78,123)', ...
    'width', 6, ...
    'dash', 'dot'), ...
  'marker', struct(...
    'opacity', 1.0, ...
    'symbol', 'square', ...
    'size', 12, ...
    'color', 'rgb(54,144,192)', ...
    'line', struct(...
      'width', 3, ...
      'color', 'darkblue')));
trace2 = struct(...
  'x', [1, 2, 3], ...
  'y', [2, 10, 12], ...
  'type', 'scatter', ...
  'name', 'Control', ...
  'line', struct(...
    'color', 'purple', ...
    'width', 4, ...
    'dash', 'dashdot'), ...
  'marker', struct(...
    'opacity', 0.9, ...
    'symbol', 'cross', ...
    'size', 16, ...
    'color', 'fuchsia', ...
    'line', struct(...
      'color', '', ...
      'width', 0)));
data = {trace0, trace1};

response = plotly(data, struct('filename', 'line-style', 'fileopt', 'overwrite'));
plot_url = response.url