signin('test-runner', '9h29fe3l0x')

trace1 = struct(...
  'x', [1, 2, 3], ...
  'y', [4, 5, 6], ...
  'name', 'yaxis1 data');
trace2 = struct(...
  'x', [2, 3, 4], ...
  'y', [40, 50, 60], ...
  'name', 'yaxis2 data', ...
  'yaxis', 'y2');
trace3 = struct(...
  'x', [3, 4, 5], ...
  'y', [400, 500, 600], ...
  'name', 'yaxis3 data', ...
  'yaxis', 'y3');
trace4 = struct(...
  'x', [4, 5, 6], ...
  'y', [40000, 50000, 60000], ...
  'name', 'yaxis4 data', ...
  'yaxis', 'y4');
trace5 = struct(...
  'x', [5, 6, 7], ...
  'y', [400000, 500000, 600000], ...
  'name', 'yaxis5 data', ...
  'yaxis', 'y5');
trace6 = struct(...
  'x', [6, 7, 8], ...
  'y', [4000000, 5000000, 6000000], ...
  'name', 'yaxis6 data', ...
  'yaxis', 'y6');
data = {trace0, trace1, trace2, trace3, trace4, trace5};

layout = struct(...
    'width', 800, ...
    'xaxis', struct('domain', [0.3, 0.7]), ...
    'yaxis', struct(...
      'title', 'yaxis title', ...
      'titlefont', struct('color', '#1f77b4'), ...
      'tickfont', struct('color', '#1f77b4')), ...
    'yaxis2', struct(...
      'overlaying', 'y', ...
      'side', 'left', ...
      'anchor', 'free', ...
      'position', 0.15, ...
      'title', 'yaxis2 title', ...
      'titlefont', struct('color', '#ff7f0e'), ...
      'tickfont', struct('color', '#ff7f0e')), ...
    'yaxis3', struct(...
      'overlaying', 'y', ...
      'side', 'left', ...
      'anchor', 'free', ...
      'position', 0, ...
      'title', 'yaxis3 title', ...
      'titlefont', struct('color', '#2ca02c'), ...
      'tickfont', struct('color', '#2ca02c')), ...
    'yaxis4', struct(...
      'overlaying', 'y', ...
      'side', 'right', ...
      'anchor', 'x', ...
      'title', 'yaxis4 title', ...
      'titlefont', struct('color', '#d62728'), ...
      'tickfont', struct('color', '#d62728')), ...
    'yaxis5', struct(...
      'overlaying', 'y', ...
      'side', 'right', ...
      'anchor', 'free', ...
      'position', 0.85, ...
      'title', 'yaxis5 title', ...
      'titlefont', struct('color', '#9467bd'), ...
      'tickfont', struct('color', '#9467bd')), ...
    'yaxis6', struct(...
      'overlaying', 'y', ...
      'side', 'right', ...
      'anchor', 'free', ...
      'position', 1.0, ...
      'title', 'yaxis6 title', ...
      'titlefont', struct('color', '#8c564b'), ...
      'tickfont', struct('color', '#8c564b')), ...
    'title', 'multiple y-axes example');

response = plotly(data, struct('layout', layout, 'filename', 'multiple-axes-multiple', 'fileopt', 'overwrite'));
plot_url = response.url