signin('test-runner', '9h29fe3l0x')

x0 = randn(500,1);
x1 = randn(500,1)+1;

trace1 = struct(...
  'x', x0, ...
  'type', 'histogram', ...
  'opacity', 0.75);
trace2 = struct(...
  'x', x1, ...
  'type', 'histogram', ...
  'opacity', 0.75);
data = {trace0, trace1};

layout = struct('barmode', 'overlay');

response = plotly(data, struct('layout', layout, 'filename', 'overlaid-histogram', 'fileopt', 'overwrite'));
plot_url = response.url