signin('test-runner', '9h29fe3l0x')

data = {...
  struct(...
    'x', [0, 1, 2], ...
    'y', [6, 10, 2], ...
    'error_y', struct(...
      'type', 'percent', ...
      'value', 50, ...
      'visible', true))...
};

response = plotly(data, struct('filename', 'percent-error-bar', 'fileopt', 'overwrite'));
plot_url = response.url