signin('test-runner', '9h29fe3l0x')

data = {...
  struct(...
    'x', [0, 2, 4], ...
    'y', [0, 4, 2], ...
    'type', 'scatter')...
};

response = plotly(data, struct('filename', 'privacy-false', 'fileopt', 'overwrite', 'world_readable', 'false'));
plot_url = response.url