signin('test-runner', '9h29fe3l0x')

trace1 = struct(...
  'x', [0, 1, 2], ...
  'y', [10, 11, 12]);
trace2 = struct(...
  'x', [2, 3, 4], ...
  'y', [100, 110, 120], ...
  'yaxis', 'y2');
trace3 = struct(...
  'x', [3, 4, 5], ...
  'y', [1000, 1100, 1200], ...
  'yaxis', 'y3');
data = {trace0, trace1, trace2};

layout = struct(...
    'yaxis', struct('domain', [0, 0.33]), ...
    'yaxis2', struct('domain', [0.33, 0.66]), ...
    'yaxis3', struct('domain', [0.66, 1]), ...
    'legend', struct('traceorder', 'reversed'));

response = plotly(data, struct('layout', layout, 'filename', 'stacked-coupled-subplots', 'fileopt', 'overwrite'));
plot_url = response.url