signin('test-runner', '9h29fe3l0x')

trace1 = struct(...
  'x', [0, 1, 2, 3, 4, 5, 6, 7, 8], ...
  'y', [0, 1, 2, 3, 4, 5, 6, 7, 8], ...
  'name', 'Name of Trace 1');
trace2 = struct(...
  'x', [0, 1, 2, 3, 4, 5, 6, 7, 8], ...
  'y', [1, 0, 3, 2, 5, 4, 7, 6, 8], ...
  'name', 'Name of Trace 2');
data = {trace0, trace1};

layout = struct(...
    'title', 'Plot Title', ...
    'xaxis', struct(...
      'title', 'x Axis', ...
      'titlefont', struct(...
        'color', '#7f7f7f', ...
        'family', 'Courier New, monospace', ...
        'size', 18)), ...
    'yaxis', struct(...
      'title', 'y Axis', ...
      'titlefont', struct(...
        'color', '#7f7f7f', ...
        'family', 'Courier New, monospace', ...
        'size', 18)));

response = plotly(data, struct('layout', layout, 'filename', 'styling-names', 'fileopt', 'overwrite'));
plot_url = response.url