---
title: Range Sliders and Selectors in R | Examples | Plotly
name: Range Sliders and Selectors
permalink: r/Range-sliders-selectors
description: How to use range-sliders and range-selectors in R
layout: base
thumbnail: thumbnail/sliders.jpg
language: r
page_type: example_index
has_thumbnail: true
display_as: chart_type
order: 1
output: 
  html_document: 
    keep_md: yes
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = F)
Sys.setenv("plotly_username" = "RPlotBot")
Sys.setenv("plotly_api_key" = "q0lz6r5efr")
```
Now you can implement range sliders and range selectors in your Plotly graphs with R!!!

New to our R API?
Learn about API authentication here: https://plot.ly/r/getting-started 
Find your api_key here: https://plot.ly/settings/api

```{r, message=FALSE}
library(plotly)
library(quantmod)

# Download some data
getSymbols(Symbols = c("AAPL", "MSFT"))

ds <- data.frame(Date = index(AAPL), AAPL[,6], MSFT[,6])

plot_ly(ds, x = Date, y = AAPL.Adjusted, mode = "lines + markers", name = "Apple") %>% 
  add_trace(x = Date, y = MSFT.Adjusted, name = "Microsoft") %>% 
  layout(
    title = "Stock Prices",
    xaxis = list(
      rangeselector = list(
        buttons = list(
          list(
            count = 3, 
            label = "3 mo", 
            step = "month",
            stepmode = "backward"),
          list(
            count = 6, 
            label = "6 mo", 
            step = "month",
            stepmode = "backward"),
          list(
            count = 1, 
            label = "1 yr", 
            step = "year",
            stepmode = "backward"),
          list(
            count = 1, 
            label = "YTD", 
            step = "year",
            stepmode = "todate"),
          list(step = "all"))),
      
      rangeslider = list(type = "date")),
    
    yaxis = list(title = "Price"))
```

```{r, echo = F}
p <- plot_ly(ds, x = Date, y = AAPL.Adjusted, mode = "lines + markers", name = "Apple") %>% 
  add_trace(x = Date, y = MSFT.Adjusted, name = "Microsoft") %>% 
  layout(
    title = "Stock Prices",
    xaxis = list(
      rangeselector = list(
        buttons = list(
          list(
            count = 3, 
            label = "3 mo", 
            step = "month",
            stepmode = "backward"),
          list(
            count = 6, 
            label = "6 mo", 
            step = "month",
            stepmode = "backward"),
          list(
            count = 1, 
            label = "1 yr", 
            step = "year",
            stepmode = "backward"),
          list(
            count = 1, 
            label = "YTD", 
            step = "year",
            stepmode = "todate"),
          list(step = "all"))),
      
      rangeslider = list(type = "date")),
    
    yaxis = list(title = "Price"))

plotly_POST(p, "r-range-selector-slider")
```
