---
title: WebGL vs SVG| Examples | Plotly
name: WebGL vs SVG in R
permalink: r/webgl-vs-svg/
description: How to create plots using WebGL
layout: user-guide
language: r
page_type: example_index
has_thumbnail: true
display_as: get_request
output: 
  html_document: 
    highlight: null
    keep_md: yes
    theme: null
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, eval = F)
Sys.setenv("plotly_username"="RPlotBot")
Sys.setenv("plotly_api_key"="q0lz6r5efr")
``` 

# Compare WebGL and SVG in R

### Scatterplots with 75000 random points

### WebGL
```{r}
library(plotly)

n <- 75000
x <- rnorm(n)
y <- 2*x + rnorm(n, sd = 5)

p <- plot_ly(x = x, y = y, type = "scattergl", mode = "markers", marker = list(line = list(width = 2)))
p
```

<iframe src="https://plot.ly/~RPlotBot/2869"width="900px" height="600px" scrolling="no" seamless="seamless"></iframe>

### SVG 
> The draw time for this plot will be slow for all clients.

```{r}
library(plotly)

n <- 75000
x <- rnorm(n)
y <- 2*x + rnorm(n, sd = 5)

p <- plot_ly(x = x, y = y, type = "scatter", mode = "markers", marker = list(line = list(width = 2)))
p
```

<iframe src="https://plot.ly/~RPlotBot/2871/y-vs-x/" width="900px" height="600px" scrolling="no" seamless="seamless"></iframe>

# References
See:
- [scattergl](https://plot.ly/r/reference/#scattergl) 
- [scatter](https://plot.ly/r/reference/#scatter)
for more information.