% Learn about API authentication here: {BASE_URL}/matlab/getting-started
% Find your api_key here: {BASE_URL}/settings/api

x = randn(500,1);
y = randn(500,1)+1;

signin('TestBot', 'r1neazxo9w')
data = {...
  struct(...
    'x', x, ...
    'y', y, ...
    'type', 'histogram2d')...
};
response = plotly(data, struct('filename', '2d-histogram', 'fileopt', 'overwrite'));
plot_url = response.url
