signin('TestBot', 'r1neazxo9w')
x = randn(500,1);
y = randn(500,1)+1;

data = {...
  struct(...
    'x', x, ...
    'y', y, ...
    'type', 'histogram2d')...
};
response = plotly(data, struct('fileopt', 'overwrite', 'filename', '2d-histogram'));
plot_url = response.url