signin('theengineear', 'o9zlr0hy6z')

t = linspace(-1, 1.2, 2000);
x = (t.^3)+(0.3.*randn(1, 2000));
y = (t.^6)+(0.3.*randn(1, 2000));
trace1 = struct(...
  'x', x, ...
  'y', y, ...
  'name', 'points', ...
  'mode', 'markers', ...
  'marker', struct(...
    'size', 2, ...
    'color', 'rgb(102,0,0)', ...
    'opacity', 0.4), ...
  'type', 'scatter');
trace2 = struct(...
  'x', x, ...
  'y', y, ...
  'scl', 'Hot', ...
  'reversescl', true, ...
  'name', 'density', ...
  'ncontours', 20, ...
  'showscale', false, ...
  'type', 'histogram2dcontour');
trace3 = struct(...
  'x', x, ...
  'name', 'x density', ...
  'marker', struct('color', 'rgb(102,0,0)'), ...
  'yaxis', 'y2', ...
  'type', 'histogram');
trace4 = struct(...
  'y', y, ...
  'name', 'y density', ...
  'marker', struct('color', 'rgb(102,0,0)'), ...
  'xaxis', 'x2', ...
  'type', 'histogram');
data = {trace1, trace2, trace3, trace4};
layout = struct(...
    'xaxis', struct(...
      'domain', [0, 0.85], ...
      'showgrid', false, ...
      'zeroline', false), ...
    'yaxis', struct(...
      'domain', [0, 0.85], ...
      'showgrid', false, ...
      'zeroline', false), ...
    'width', 600, ...
    'height', 550, ...
    'autosize', false, ...
    'margin', struct('t', 50), ...
    'hovermode', 'closest', ...
    'bargap', 0, ...
    'showlegend', false, ...
    'xaxis2', struct(...
      'domain', [0.85, 1], ...
      'showgrid', false, ...
      'zeroline', false), ...
    'yaxis2', struct(...
      'domain', [0.85, 1], ...
      'showgrid', false, ...
      'zeroline', false));

response = plotly(data, struct('layout', layout, 'filename', '2dhistogram-contour-subplots', 'fileopt', 'overwrite', 'auto_open', 'false'));
plot_url = response.url