signin('TestBot', 'r1neazxo9w')

data = {...
  struct(...
    'x', [2, 4, 6], ...
    'y', [-3, 0, 3], ...
    'type', 'scatter')...
};
layout = struct(...
    'xaxis', struct(...
      'autorange', true, ...
      'rangemode', 'tozero'), ...
    'yaxis', struct(...
      'autorange', true, ...
      'rangemode', 'nonnegative'), ...
    'showlegend', false);

response = plotly(data, struct('layout', layout, 'filename', 'axes-range-mode', 'fileopt', 'overwrite', 'auto_open', 'false'));
plot_url = response.url