signin('TestBot', 'r1neazxo9w')

data = {...
  struct(...
    'x', [1, 2], ...
    'y', [1, 2], ...
    'type', 'scatter')...
};
layout = struct('xaxis', struct('autorange', 'reversed'));
response = plotly(data, struct('layout', layout, 'fileopt', 'overwrite', 'filename', 'axes-reversed'));
plot_url = response.url