signin('TestBot', 'r1neazxo9w')
data = {...
  struct(...
    'x', [2, 4, 6], ...
    'y', [-3, 0, 3], ...
    'type', 'scatter')...
};
layout = struct(...
    'showlegend', false, ...
    'xaxis', struct(...
      'rangemode', 'tozero', ...
      'autorange', true), ...
    'yaxis', struct(...
      'rangemode', 'nonnegative', ...
      'autorange', true));
response = plotly(data, struct('layout', layout, 'auto_open', false, 'fileopt', 'overwrite', 'filename', 'axes-range-mode'));
plot_url = response.url