signin('theengineear', 'o9zlr0hy6z')

data = {...
  struct(...
    'x', [1, 2], ...
    'y', [1, 2], ...
    'type', 'scatter')...
};
layout = struct('xaxis', struct('autorange', 'reversed'));

response = plotly(data, struct('layout', layout, 'filename', 'axes-reversed', 'fileopt', 'overwrite', 'auto_open', 'false'));
plot_url = response.url