% Learn about API authentication here: {BASE_URL}/matlab/getting-started
% Find your api_key here: {BASE_URL}/settings/api

signin('TestBot', 'r1neazxo9w')
trace1 = struct(...
  'x', [0, 1, 2, 3, 4, 5], ...
  'y', [1.5, 1, 1.3, 0.7, 0.8, 0.9], ...
  'type', 'scatter');
trace2 = struct(...
  'x', [0, 1, 2, 3, 4, 5], ...
  'y', [1, 0.5, 0.7, -1.2, 0.3, 0.4], ...
  'type', 'bar');
data = {trace1, trace2};
response = plotly(data, struct('filename', 'bar-line', 'fileopt', 'overwrite'));
plot_url = response.url
