% Learn about API authentication here: plot.ly/matlab/getting-started
% Find your api_key here: plot.ly/settings/api

signin('TestBot', 'r1neazxo9w')


data = {...
  struct(...
    'x', { {'giraffes', 'orangutans', 'monkeys'} }, ...
    'y', [20, 14, 23], ...
    'type', 'bar')...
};
response = plotly(data, struct('filename', 'basic-bar', 'fileopt', 'overwrite'));
plot_url = response.url
