signin('TestBot', 'r1neazxo9w')
x = randn(500,1);

data = {...
  struct(...
    'x', x, ...
    'type', 'histogram')...
};
response = plotly(data, struct('fileopt', 'overwrite', 'filename', 'basic-histogram'));
plot_url = response.url