% Learn about API authentication here: {BASE_URL}/matlab/getting-started
% Find your api_key here: {BASE_URL}/settings/api

signin('TestBot', 'r1neazxo9w')
data = {...
  struct(...
    'x', [0, 1, 2], ...
    'y', [6, 10, 2], ...
    'error_y', struct(...
      'type', 'data', ...
      'array', [1, 2, 3], ...
      'visible', true), ...
    'type', 'scatter')...
};
response = plotly(data, struct('filename', 'basic-error-bar', 'fileopt', 'overwrite'));
plot_url = response.url
