signin('TestBot', 'r1neazxo9w')

data = {...
  struct(...
    'z', [1, 20, 30; 20, 1, 60; 30, 60, 1], ...
    'type', 'heatmap')...
};

response = plotly(data, struct('filename', 'basic-heatmap', 'fileopt', 'overwrite', 'auto_open', 'false'));
plot_url = response.url