signin('TestBot', 'r1neazxo9w')

data = {...
  struct(...
    'x', [1, 2, 3, 4], ...
    'y', [2, 1, 3, 4], ...
    'error_x', struct(...
      'type', 'percent', ...
      'value', 10), ...
    'type', 'scatter')...
};
response = plotly(data, struct('filename', 'error-bar-horizontal', 'fileopt', 'overwrite'));
plot_url = response.url
