signin('theengineear', 'o9zlr0hy6z')

trace1 = struct(...
  'x', { {'Trial 1', 'Trial 2', 'Trial 3'} }, ...
  'y', [3, 6, 4], ...
  'name', 'Control', ...
  'error_y', struct(...
    'array', [1, 0.5, 1.5], ...
    'type', 'data', ...
    'visible', true), ...
  'type', 'bar');
trace2 = struct(...
  'x', { {'Trial 1', 'Trial 2', 'Trial 3'} }, ...
  'y', [4, 7, 3], ...
  'name', 'Experimental', ...
  'error_y', struct(...
    'array', [0.5, 1, 2], ...
    'type', 'data', ...
    'visible', true), ...
  'type', 'bar');
data = {trace1, trace2};
layout = struct('barmode', 'group');

response = plotly(data, struct('layout', layout, 'filename', 'error-bar-bar', 'fileopt', 'overwrite', 'auto_open', 'false'));
plot_url = response.url