signin('TestBot', 'r1neazxo9w')

data = {...
  struct(...
    'x', [1, 2, 3, 4], ...
    'y', [2, 1, 3, 4], ...
    'error_x', struct(...
      'value', 10, ...
      'type', 'percent'), ...
    'type', 'scatter')...
};

response = plotly(data, struct('filename', 'error-bar-horizontal', 'fileopt', 'overwrite', 'auto_open', 'false'));
plot_url = response.url