signin('theengineear', 'o9zlr0hy6z')

y = randn(500,1);
data = {...
  struct(...
    'y', y, ...
    'type', 'histogram')...
};

response = plotly(data, struct('filename', 'horizontal-histogram', 'fileopt', 'overwrite', 'auto_open', 'false'));
plot_url = response.url