signin('theengineear', 'o9zlr0hy6z')

trace1 = struct(...
  'x', [1, 2, 3, 4], ...
  'y', [10, 15, 13, 17], ...
  'mode', 'markers', ...
  'type', 'scatter');
trace2 = struct(...
  'x', [2, 3, 4, 5], ...
  'y', [16, 5, 11, 9], ...
  'mode', 'lines', ...
  'type', 'scatter');
trace3 = struct(...
  'x', [1, 2, 3, 4], ...
  'y', [12, 9, 15, 12], ...
  'mode', 'lines+markers', ...
  'type', 'scatter');
data = {trace1, trace2, trace3};

response = plotly(data, struct('filename', 'line-scatter', 'fileopt', 'overwrite', 'auto_open', 'false'));
plot_url = response.url