% Learn about API authentication here: {BASE_URL}/matlab/getting-started
% Find your api_key here: {BASE_URL}/settings/api

signin('TestBot', 'r1neazxo9w')
data = {...
  struct(...
    'x', [0, 2, 4], ...
    'y', [0, 4, 2], ...
    'type', 'scatter')...
};
response = plotly(data, struct('filename', 'privacy-true', 'world_readable', true, 'fileopt', 'overwrite'));
plot_url = response.url
