signin('TestBot', 'r1neazxo9w')

data = {...
  struct(...
    'x', [0, 2, 4], ...
    'y', [0, 4, 2], ...
    'type', 'scatter')...
};
response = plotly(data, struct('filename', 'privacy-false', 'world_readable', false, 'fileopt', 'overwrite'));
plot_url = response.url
