signin('TestBot', 'r1neazxo9w')

data = {...
  struct(...
    'x', [0, 1, 2, 3, 4, 5, 6, 7, 8], ...
    'y', [0, 1, 2, 3, 4, 5, 6, 7, 8], ...
    'type', 'scatter')...
};
layout = struct(...
    'autosize', false, ...
    'width', 500, ...
    'height', 500, ...
    'margin', struct(...
      'l', 50, ...
      'r', 50, ...
      'b', 100, ...
      't', 100, ...
      'pad', 4), ...
    'paper_bgcolor', '#7f7f7f', ...
    'plot_bgcolor', '#c7c7c7');
response = plotly(data, struct('layout', layout, 'fileopt', 'overwrite', 'filename', 'size-margins'));
plot_url = response.url