signin('TestBot', 'r1neazxo9w')

trace1 = struct(...
  'x', [0, 1, 2], ...
  'y', [1, 1, 1], ...
  'text', { {'Text A', 'Text B', 'Text C'} }, ...
  'textposition', 'top right', ...
  'name', 'Lines, Markers and Text', ...
  'mode', 'lines+markers+text', ...
  'textfont', struct(...
    'family', 'sans serif', ...
    'size', 18, ...
    'color', '#1f77b4'), ...
  'type', 'scatter');
trace2 = struct(...
  'x', [0, 1, 2], ...
  'y', [2, 2, 2], ...
  'text', { {'Text G', 'Text H', 'Text I'} }, ...
  'textposition', 'bottom', ...
  'name', 'Lines and Text', ...
  'mode', 'lines+markers+text', ...
  'textfont', struct(...
    'family', 'sans serif', ...
    'size', 18, ...
    'color', '#ff7f0e'), ...
  'type', 'scatter');
data = {trace1, trace2};
layout = struct('showlegend', false);

response = plotly(data, struct('layout', layout, 'filename', 'text-chart-styling', 'fileopt', 'overwrite', 'auto_open', 'false'));
plot_url = response.url